project:
  type: website

website:
  title: "Stat 20"
  search: false
  site-url: "https://www.stat20.org/"
  repo-url: "https://github.com/stat20/website"
  page-navigation: true
  navbar:
    background: white
    foreground: "gray-800"
    right:
      - href: syllabus.qmd
        text: FAQ
      # - href: schedule.qmd
      #   text: Schedule
      # - href: labs/index.qmd
      #   text: Labs

format:
  html:
    theme: 
      - sandstone
      - styles.scss

execute:
  freeze: auto
