project:
  type: website

website:
  title: "Stat 20"
  navbar:
    search: false
    background: white
    foreground: black
    right:
      - href: syllabus.qmd
        text: FAQ
      # - href: schedule.qmd
      #   text: Schedule
      # - href: labs/index.qmd
      #   text: Labs

format:
  html:
    theme: 
      - sandstone
      - styles.scss



