project:
  type: website

website:
  title: "Stat 20"
  search: false
  site-url: "https://www.stat20.org/"
  repo-url: "https://github.com/stat20/website"
  page-navigation: true
  navbar:
    background: white
    foreground: "gray-800"
    right:
      - text: FAQ
        href: syllabus.qmd
      - text: Schedule
        href: schedule/index.qmd
      - text: Notes
        href: notes/index.qmd
      - text: Labs
        href: labs/index.qmd
  # sidebar:
  #   - id: schedule
  #     title: "Schedule"
  #     style: "floating"
  #     align: left
  #     contents:
  #         - text: "Schedule"
  #           href: schedule/index.qmd
  #         - text: "1. Questions and Data"
  #           href: schedule/1-questions-and-data/index.qmd
  #         - text: "2. Describing Data"
  #           href: schedule/2-describing-data/index.qmd
  #         - text: "3. Predictions"
  #           href: schedule/3-predictions/index.qmd
  #         - text: "4. Generalizations"
  #           href: schedule/4-generalizations/index.qmd
  #         - text: "5. Causality"
  #           href: schedule/5-causality/index.qmd

format:
  html:
    theme: 
      - sandstone
      - assets/styles.scss

execute:
  freeze: auto
