project:
  type: website

website:
  title: "Stat 20"
  description: "this is a descr"
  search: false
  site-url: "https://www.stat20.org/"
  repo-url: "https://github.com/stat20/website"
  favicon: assets/favicon.ico
  image: assets/stat20-hex-small.png
  open-graph: true
  twitter-card: true
  page-navigation: true
  navbar:
    title: " "
    logo: assets/stat20-hex-small.png
    background: white
    foreground: "gray-800"
    collapse-below: sm
    left:
      - text: FAQ
        href: syllabus.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Notes
        href: notes.qmd
      - text: Labs
        href: labs.qmd
    right:
      - text: "{{< fa comments >}}"
        href: https://app.perusall.com/courses/introduction-to-probability-and-statistics-fall-2022
        aria-label: Perusall Discussion Forum
      - text: "{{< fa chart-column >}}"
        href: https://www.gradescope.com/courses/416233
        aria-label: Gradescope
      - text: "{{< fa brands r-project >}}"
        href: https://stat20.datahub.berkeley.edu/
        aria-label: RStudio
  page-footer: 
    background: white
    foreground: "gray-800"
    border: false
    center: 
      - text: "{{< fa comments >}}"
        href: https://app.perusall.com/courses/introduction-to-probability-and-statistics-fall-2022
        aria-label: Perusall Discussion Forum
      - text: "{{< fa chart-column >}}"
        href: https://www.gradescope.com/courses/416233
        aria-label: Gradescope
      - text: "{{< fa brands r-project >}}"
        href: https://stat20.datahub.berkeley.edu/
        aria-label: RStudio
    right:
      - text: This is an open source project.
        href: license.qmd
  # sidebar:
  #   - id: schedule
  #     title: "Schedule"
  #     style: "floating"
  #     align: left
  #     contents:
  #         - text: "Schedule"
  #           href: schedule/index.qmd
  #         - text: "1. Questions and Data"
  #           href: schedule/1-questions-and-data/index.qmd
  #         - text: "2. Describing Data"
  #           href: schedule/2-describing-data/index.qmd
  #         - text: "3. Predictions"
  #           href: schedule/3-predictions/index.qmd
  #         - text: "4. Generalizations"
  #           href: schedule/4-generalizations/index.qmd
  #         - text: "5. Causality"
  #           href: schedule/5-causality/index.qmd

format:
  html:
    theme: 
      - sandstone
      - assets/styles.scss

execute:
  freeze: auto
